# Generated by Django 2.1.3 on 2018-11-22 09:45

from django.db import migrations, models
import scand.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('accoff', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
                ('docref', models.CharField(max_length=10)),
                ('years', models.CharField(max_length=9)),
                ('pagenum', models.CharField(max_length=5)),
                ('refnum', models.CharField(max_length=15)),
                ('pernum', models.CharField(max_length=8)),
                ('attr1', models.CharField(max_length=30)),
                ('attr2', models.CharField(max_length=30)),
                ('attr3', models.CharField(max_length=30)),
                ('attr4', models.CharField(max_length=30)),
                ('attr5', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=scand.models.ImageTag.get_upload_path)),
            ],
        ),
    ]
