# Generated by Django 2.1.3 on 2019-02-06 06:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scand', '0005_remove_imagetag_image_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetag',
            name='years',
        ),
        migrations.AddField(
            model_name='imagetag',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='status',
            field=models.CharField(blank=True, choices=[('01', 'created'), ('02', 'proofread'), ('03', 'active')], max_length=2),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='year_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2099), django.core.validators.MinValueValidator(1980)], verbose_name='Start Year'),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='year_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2099), django.core.validators.MinValueValidator(1980)], verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='accoff',
            field=models.CharField(blank=True, max_length=200, verbose_name='Office / Department'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='attr1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Extra Attribute'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='attr2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Extra Attribute'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='attr3',
            field=models.CharField(blank=True, max_length=30, verbose_name='Extra Attribute'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='attr4',
            field=models.CharField(blank=True, max_length=30, verbose_name='Extra Attribute'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='attr5',
            field=models.CharField(blank=True, max_length=30, verbose_name='Extra Attribute'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='company',
            field=models.CharField(blank=True, max_length=50, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='docref',
            field=models.CharField(blank=True, max_length=10, verbose_name='Document Reference'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='pagenum',
            field=models.CharField(blank=True, max_length=5, verbose_name='Page Number'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='pernum',
            field=models.CharField(blank=True, max_length=8, verbose_name='Personnel ID Number'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='refnum',
            field=models.CharField(blank=True, max_length=15, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='section',
            field=models.CharField(blank=True, max_length=200, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='scand.LowerCaseTaggedItem', to='scand.LowerCaseTag', verbose_name='Extra Tags'),
        ),
    ]
