# Generated by Django 2.1.3 on 2019-02-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scand', '0006_auto_20190206_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetag',
            name='year_from',
        ),
        migrations.RemoveField(
            model_name='imagetag',
            name='year_to',
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Till Date'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='From Date'),
        ),
    ]
