# Generated by Django 2.1.3 on 2019-02-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scand', '0008_auto_20190206_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
