# Generated by Django 2.1.3 on 2019-02-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scand', '0009_auto_20190207_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='changed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
