# Generated by Django 2.1.3 on 2019-02-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scand', '0011_auto_20190207_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
