# Generated by Django 2.1.3 on 2019-02-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scand', '0013_auto_20190207_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetag',
            options={'permissions': (('can_approve', 'Can Approve'),)},
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='accoff',
            field=models.CharField(blank=True, max_length=200, verbose_name='Office / Deptt:'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='docref',
            field=models.CharField(blank=True, max_length=10, verbose_name='Document Ref.'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='pernum',
            field=models.CharField(blank=True, max_length=8, verbose_name='Personnel Id No.'),
        ),
    ]
