# Generated by Django 2.1.3 on 2019-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scand', '0016_auto_20190215_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='accoff',
            field=models.CharField(help_text='required field', max_length=200, verbose_name='Office / Deptt: ❋'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='company',
            field=models.CharField(help_text='required field', max_length=200, verbose_name='Company ❋'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='docref',
            field=models.CharField(help_text='required field', max_length=10, verbose_name='Document Ref. ❋'),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='section',
            field=models.CharField(help_text='required field', max_length=200, verbose_name='Section ❋'),
        ),
    ]
