# Generated by Django 2.1.3 on 2019-02-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scand', '0019_auto_20190218_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='is_forwarded',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='is_reverted',
            field=models.BooleanField(default=False),
        ),
    ]
