# Generated by Django 2.1.3 on 2019-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scand', '0020_auto_20190218_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
