# Generated by Django 2.1.3 on 2019-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scand', '0022_auto_20190218_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Initial'), (1, 'Created'), (2, 'Proofread'), (3, 'Active')], null=True),
        ),
    ]
