# Generated by Django 2.1.3 on 2019-02-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default=False, max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(default=False, max_length=100, verbose_name='Last Name'),
        ),
    ]
