# Generated by Django 2.1.3 on 2019-02-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lname',
        ),
    ]
